### ISSUE TITLE
Change List to scala.Seq in trees

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1001]
A recent refactoring changed all occurrences of immutable.Seq to List in both syntactic and semantic API. However, we quickly figured that this may not be good enough for Database, so we changed Database.entries from List to scala.Seq. 

I propose that we make the same change to trees, too. Previous discussion: https://github.com/scalameta/scalameta/pull/907#issuecomment-306210194. In addition to all those arguments in favor of scala.Seq, we now have an argument of consistency.

**Comment by ShaneDelmore** [comment]
The main argument I hear against Seq is that it isn’t immutable by default but the strawman collections proposal has Seq defaulting to be immutable (tentatively scheduled for 2.13) in which case the original complaint may not last that much longer.

**Comment by olafurpg** [comment]
I am not sure we need so much consistency in our collection choices for unrelated data structures across modules. I think it's fine to use List on trees and Seq in Database. Tokens already use arrays, and for good reasons. Data structures have different shapes and requirements. My experience is that

1) databases can become large (>30.000 elements)
2) the surface code I write against database is quite small (load + dump)

Trees are used differently

1) each List is almost always small
2) the surface code I write against trees is large (repl, rewrites, macros)

**Comment by DavidDudson** [comment]
Here's my opinion.

The entire scalameta tree hierarchy must retain immutability, otherwise no consumer of the scalameta api can reason about the internals of scalameta. This requires all fields to have some immutable.Seq type.

If we allow inputs of type scala.Seq/ we immediately have to copy that to an immutable.Seq of some kind unless it is already an immutable.Seq.

@ShaneDelmore Correct me if I am wrong, but I was under the impression that scala.Seq's apply method was changing, not that scala.Seq's api was changing, thus if you will still be able to have a scala.Seq that is mutable.

In regards to consistency, I don't think collection types should be decided because of consistency. As @olafurpg points out, the semantic database is a completely separate api with it's own needs. List is a great choice for Tree's

We could definitely add setters to Tree fields that are of type List, so that we can create Tree subtypes with scala.Seq. We just would need to defensively copy anything that's not an immutable.Seq.

**Comment by ShaneDelmore** [comment]
@DavidDudson I was mistaken, there is only a suggestion to make the strawman Seq immutable.  
https://github.com/scala/collection-strawman/issues/149

I upvoted this based on the thinking that scala Seq was moving towards immutable, if that doesn’t end up happening then I agree I would prefer List to have the immutability guarantee.

**Comment by xeno-by** [comment]
Allright, let's keep lists in trees. 

Regarding List becoming Seq in Database. I accepted that PR (see https://github.com/scalameta/scalameta/issues/996 for details) when I just woke up and soon enough started regretting that decision. 

My reason for regret is that the only argument provided in favor of the change was performance-related, but it wasn't accompanied by benchmark results. Our experience with scalac taught me that gut feeling doesn't always work well in the matters of performance, so we should've waited for concrete numbers.

I don't want to make any more hasty decisions, so let's keep the status quo, but let's see whether Lists are as bad as they are touted to be. I've opened a ticket to investigate that: https://github.com/scalameta/scalameta/issues/1012.
