### ISSUE TITLE
Semantic API: any way to find definition?

### ISSUE THREAD

**Issue by loskutov** [scalameta/scalameta#1061]
Given a `Symbol`/`Denotation`/fqname corresponding to a method, is there a way to know in which class it was declared/defined?

**Comment by olafurpg** [comment]
`ResolvedName.isDefinition`, see schema https://github.com/scalameta/scalameta/blob/d2c6efecef6f27e9bb8855d1d12fe894a69fea9e/langmeta/shared/src/main/protobuf/semanticdb.proto#L24

With that data, it's possible to build a reverse lookup index (something like `Map[Symbol, Tree]`) to go from a symbol to its definition tree. There is no out-of-the-box solution to "jump to definition", since it really depends on the application how you want to load/query the semanticdb data. In metadoc, we pre-compute an index for Symbol -> Position lookups https://github.com/scalameta/metadoc/blob/196c002a5cb40368c45d78bdaef457be711e15b1/metadoc-core/src/main/protobuf/metadoc.proto#L12
