### ISSUE TITLE
Incorrect Mod.Implicit() equality

### ISSUE THREAD

**Issue by a-nigredo** [scalameta/scalameta#1062]
`Mod.Implicit() == Mod.Implicit()` return false but have to be true. Thus it is not possible e.g. find implicit param in def via contains method in a sequence. 
Whereas `Mod.Implicit().children == Mod.Implicit().children` works fine

**Comment by xeno-by** [comment]
There may be different notions of equality for trees: syntactic, structural, semantic, etc. Defaulting to one of those notions may be confusing for some users which may expect something else. That's why we decided to have Tree.== to be the same as Tree.eq.

In order to compare trees structurally, Scalameta users have to use pattern matching. If you have semantic API available, you can also use `.isImplicit`.

**Comment by DavidDudson** [comment]
@a-nigredo Also it may be worth noting that scalameta.contrib has the implicit method `isEqual` on all tree's which uses structural equality by default.

`Mod.Implicit() isEqual Mod.Implicit()` would return true
