### ISSUE TITLE
Consider merging some of our subprojects

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1092]
As @olafurpg says, our build is quite heavyweight, which leads to serious performance problems on the sbt side. I think, good candidates for merging would be io+inputs+semanticdb+langmeta, dialects+parsers, io+inputs+semanticdb+scalameta.

**Comment by xeno-by** [comment]
Merging will allow us to turn `Input.Denotation.symbol` into a `Symbol`, which is nice.

**Comment by olafurpg** [comment]
I merge all langmeta modules in #1094, this enables the Input.Denotation.symbol fix. I will leave the other modules separate since 

- some token/parser macros hardcode scala.meta.inputs
- it doesn't provide any direct value like Input.Denotation.symbol

We should be able to merge those modules later without breaking binary compatibility.

**Comment by olafurpg** [comment]
Just for the record, I am personally a big fan of fine-grained target. I've used bazel and I loved it, single file targets are amazing and help prevent cyclic dependencies in your codebase. However, unfortunately I think sbt accommodates fine grained targets badly.

**Comment by xeno-by** [comment]
Thanks for the update! If this issue is no longer immediately actionable, let's close it?

**Comment by olafurpg** [comment]
Agreed.
