### ISSUE TITLE
Symbol interpolator

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1098]
It would be nice to have a `symbol` interpolator that is a whitebox macro
```scala
symbol"_root_.a.": Symbol.Global
```
This would be helpful in scalafix.

**Comment by xeno-by** [comment]
During today's meeting, we decided that Scalafix won't benefit from the functionality as proposed above. It turns out that in Scalafix, they are using shortened symbol ids inside interpolators, e.g. `symbol"a"` instead of `symbol"_root_.a."`. 

While usecase-specific shorthands are great to improve UX for Scalafix users, I don't think such shortcuts have a place in Scalameta, whose goal in my opinion is to provide a usecase-agnostic model for Scala.
