### ISSUE TITLE
Type inference using scalameta?

### ISSUE THREAD

**Issue by jonas-db** [scalameta/scalameta#1199]
Is it possible to transform partially typed source code to fully typed source code with scalameta or any other tool?

For example:

```
val i:Int = 2
val z = i + 1
```

to

```
val i:Int = 2
val z:Int = i + 1
```

**Comment by olafurpg** [comment]
You mean something like https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes or do you also want inferred type parameters to be made explicit?

**Comment by jonas-db** [comment]
@olafurpg Looks interesting, I'll check it out. I just want to make any inferred type explicit in the source code, doesn't matter whether this is the result type of a function or the type of variable, ...

**Comment by olafurpg** [comment]
I've been looking into how to implement that exact problem today with scalafix :) Quick answer is that there is no plug and play at the moment since it's a tricky problem. Do you plan to commit those changes? Note that the inferred types can be quite large for many common operations. Also, what about inferred implicits and `.apply`?

**Comment by tgodzik** [comment]
This is currently implemented in ExplicitResultTypes rules, which uses the presentation compiler. We do not plan to add an option to scalameta currently.
