### ISSUE TITLE
Remove the langmeta dependency from semanticdb-scalac

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1321]
The dependency on langmeta is significantly slowing us down - both performance-wise (because we have to spend time on conversions) and productivity-wise (because new semanticdb features have to be implemented in both semanticdb3 and langmeta). Would be great to get rid of that dependency completely.

**Comment by olafurpg** [comment]
Not sure we can escape the dependency immediately, but a good first step would be to stop emitting org.langmeta.Document and go to s.TextDocument directly instead

**Comment by xeno-by** [comment]
I haven't prototyped anything yet, so I'm not sure what difficulties we may encounter with getting rid of the dependency. Any thoughts about that?

**Comment by olafurpg** [comment]
Diffs in https://github.com/scalameta/scalameta/pull/1218 and https://github.com/scalameta/scalameta/compare/master...olafurpg:perf?expand=1 are my attempts at this and may be a useful source of inspiration. The first attempt failed because of lack of benchmark infrastructure and the second failed by trying to do too much at once (drop langmeta + scalameta).

**Comment by xeno-by** [comment]
This is fixed.
