### ISSUE TITLE
Write up documentation on our CLI tools

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1447]
I suggest we create a markdown file called something like `tools.md` in https://github.com/scalameta/scalameta/tree/master/semanticdb looks.

**Comment by olafurpg** [comment]
It would be good to include --help and example usages for each tool.

**Comment by gabro** [comment]
Speaking of CLI tools, is using https://github.com/scopt/scopt an option on the table? It would simplify/normalize things like printing the help.

**Comment by olafurpg** [comment]
I've found scopt not to be very helpful since 

* --help causes `sys.exit` which makes it impossible to use as a library (from sbt-plugin, scalafix,  ...). You can configure scopt to not sys.exit on --help but in those cases you don't have a way to know if --help was called or not (unless you parse Array[String] yourself).
* it doesn't save you from writing much boilerplate compared to parsing a `List[String]` by hand.

I agree we should implement --help however. I personally don't mind writing the --help text by hand.  The interface for metap/metacp is small.

**Comment by xeno-by** [comment]
I'll write something down today and submit a pull request.

**Comment by xeno-by** [comment]
Implemented in https://github.com/scalameta/scalameta/pull/1567.
