### ISSUE TITLE
Test metacp on a large scale

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1461]
To make sure that metacp is fully ready for its mission of powering Metals indexes, we need to run it on a large corpus of jars. It can be the community build, Scaladex, etc etc - the exact implementation details are up to the implementor.

**Comment by gabro** [comment]
👌

Just to clarify, you mean a suite similar to CtashSuite but on a larger scale? I.e. checking for crashes?

**Comment by olafurpg** [comment]
Here is a corpus of 3gb of jars from the ~1000 most popular Scala libraries according to Scaladex https://drive.google.com/open?id=0B5BBsTPBxGcMQlpPQ3VrVUpndFk

I used the corpus to do analysis on what parts of the collections API are most commonly used.

> Just to clarify, you mean a suite similar to CtashSuite but on a larger scale? I.e. checking for crashes?

Correct. Primarily we want to avoid crashes since metacp is typically on a critical path for downstream tools like scalafix

**Comment by xeno-by** [comment]
@gabro Now that I'm thinking of it a bit more, it would also be useful to gather some metrics, similar to what we did in https://github.com/scalameta/scalameta/issues/1289.

**Comment by xeno-by** [comment]
We've done some internal testing at Twitter, and that resulted in a couple dozen recently submitted tickets, most of which are scheduled for 4.0.0-RC1: https://github.com/scalameta/scalameta/milestone/26. I think this counts as large-scale testing, so I'll be closing this issue.
