### ISSUE TITLE
Metacp emits reference to non-existent term symbol for val forwarders

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1625]
Using v4.0.0-M4

```scala
$ cat Foo.scala && scalac Foo.scala && metap -proto $(metacp .)
object a {
  val x: Either.type = null
}
```
```diff
- obtained
+ expected
...
  symbols {
    symbol: "_empty_.a.x()."
    kind: METHOD
    properties: 1024
    name: "x"
    accessibility {
      tag: PUBLIC
      symbol: ""
    }
    language: SCALA
    signature {
      methodSignature {
        type_parameters {
        }
        return_type {
          singleType {
            prefix {
            }
-            symbol: "scala.package.Either."
+            symbol: "scala.package.Either()."
          }
        }
      }
    }
  }
  language: SCALA
  md5: ""
}
```

**Comment by xeno-by** [comment]
@olafurpg Sorry for an unrelated question, but why is `md5` empty here?

**Comment by olafurpg** [comment]
`md5` is empty metacp doesn't include `text`

**Comment by xeno-by** [comment]
Would it make sense to hash the classfile bytes then?

**Comment by olafurpg** [comment]
I don't have a use-case for that personally, we already cache metacp processed jars by a more lightweight fingerprint (the location of the cache jar is an md5 fingerprint of filename + timestamp + file size).

**Comment by xeno-by** [comment]
@olafurpg Alright. No use case - no work to do :)

**Comment by olafurpg** [comment]
This bug popped up `metac-metacp.diff` in #1660 which might give a hint this is related to false detection of a package symbol.

**Comment by olafurpg** [comment]
The new `metacp.undefined` expect tests seems to have reproduced this issue https://github.com/scalameta/scalameta/blob/8fc2a4de80c934dcc13748bb4ebf5e52d5452cec/tests/jvm/src/test/resources/metacp.undefined#L2

**Comment by olafurpg** [comment]
I'm encountering this error a lot due to `blackbox/Context#universe.` appearing in prefix position for def macros
```
typeRef {
  prefix {
  }
  symbol: "scala/package.List#"
  type_arguments {
    typeRef {
      prefix {
        singleType {
          prefix {
            singleType {
              prefix {
              }
              symbol: "org/scalatest/DiagrammedExprMacro#context()."
            }
          }
          symbol: "scala/reflect/macros/blackbox/Context#universe."
        }
      }
      symbol: "scala/reflect/api/Trees#Tree#"
    }
  }
}
```

**Comment by olafurpg** [comment]
The problem is caused by that Scala signatures for external symbols (in singleton types) don't distinguish between `val` and `object` term names. I propose that we change the descriptor format for `val` and `var` to match `object` symbols so that the spec becomes

> For `OBJECT`, `PACKAGE_OBJECT` or `METHOD` with property `VAL` or `VAR`, concatenation of its encoded name and a dot (.).

There is no precedence for using `SymbolInformation.properties` to control the descriptor format, so it feels unsatisfying. The solution can be one of

- keep current scheme, but make `metacp` load up `SymbolInformation` for external references to compute current method descriptor when `entryType == 10` (`val` symbols can be overloaded with `def`)
- introduce `VAL` and `VAR` kinds
- bite the bullet and have inconsistency that `METHOD` symbols have different descriptor based on the `properties` field

**Comment by xeno-by** [comment]
Option 1 is a big change performance-wise, and lately we've went through several performance losses, so I'd prefer to avoid them in the near future, unless we're blocked otherwise.

Option 2 doesn't work well because there are also VAL and VAR parameters. Moreover, we don't really need to change symbol format for VAR getters and setters, because they can't be mentioned in singleton types anyway.

The only remaining option without significant downsides is option 3, which what I propose we pursue, with the following formulation in the spec:

  * ...
  * For LOCAL, unsupported.
  * For PACKAGE, concatenation of its encoded name and a forward slash (/).
  * For OBJECT or PACKAGE_OBJECT, concatenation of its encoded name and a dot (.).
  * Exceptionally, for VAL METHOD, concatenation of its encoded name and a dot (.).
  * For other METHOD, CONSTRUCTOR, or MACRO, concatenation of its encoded name, a disambiguator and a dot (.).

**Comment by olafurpg** [comment]
I agree option 3 is the least bad. I opened #1697 implementing your suggestion. Additionally, I updated the disambiguator overloading rules to treat VAL METHOD the same as OBJECT symbols.
