### ISSUE TITLE
Revert change from NonFatal to Throwable

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1730]
Commit eaced24055fa5e40a42bf3eef54662f447f92cb0 changes `NonFatal` to `Throwable` in SemanticDB-based tools. I can't approve this change since I've been badly bitten by code that catches `Throwable` swallowing critical errors I definitely want to stop the entire application.

I propose instead we additionally catch `StackOverflowException` in code paths that use recursion.

**Comment by xeno-by** [comment]
Could you give some examples of situations when `catch _: Throwable` could create problems?

**Comment by olafurpg** [comment]
Out of memory errors, stack overflow (when the configured stack size is too small) and any other VM errors. I don't think we should allow our applications to produce partial results because the VM is mis-configured. In those cases we should restart the applications with larger stack sizes and more memory.

**Comment by xeno-by** [comment]
> I don't think we should allow our applications to produce partial results because the VM is mis-configured.

Why not? We're not talking about producing partially constructed big results, we're talking about producing as many fully complete small results as possible. From what I can see, there is no downside to catching all throwables (e.g. we don't compromise on correctness), but there is an upside of having a chance to make more progress than otherwise.

To be more concrete, the commit linked in the ticket changes the following four tools: A) Metacp, B) Metai, C) Metap, D) Metac (which stands for both the semanticdb-scalac plugin and metac itself).

A-B) In the case of Metacp and Metai, individual jars/dirs are processed independently from each other, so I think it makes sense for them to succeed/fail independently from each other. 

For example, if a Metacp or a Metai classpath has several hundred entries (and internally we run on even bigger classpaths), I wouldn't want an OOM in the middle of a run to crash everything. Indeed, that OOM can be caused by a ridiculously small -Xmx, and then all subsequent entries will fail. However, what can also happen is that this particular entry was too big, but then subsequent GC frees up the memory, and other entries succeed.

This may sound overly theoretical, but this is all based on experience with running our tools on inputs that are bigger than usual. In situations like that, I found it the most productive to do one big invocation, then collect the results with all successes and errors in one place, then triage everything in one go and repeat. For big inputs, rerunning an application is not free, and it becomes problematic pretty quickly.

C) I haven't yet had a need to run Metap on huge inputs, but the same logic applies here too. If there's a bug in Metap (or a misconfiguration of the JVM) that makes metap crash on one out of thousands of files, there is a possibility that it won't affect other files. Maybe it's a minor one, but improving the UX even slightly is worth it if there are no downsides.

D) Metac is somewhat different, because this strategy can lead to partially correct results, since by default exceptions caught in handleCrash in semanticdb-scalac only produce warnings, not errors. (This also raises a tangential question of why the default is still `warning` and whether we want to change that).

However, one can argue that the very existence of `-P:semanticdb:failures` encourages partially correct results, so it's not the problem of `catch _: Throwable`. However, I don't feel strongly about this particular tool, so this particular point is fine to me either way.

**Summary.** It would seem that the introduced change is a strict UX improvement (no downsides, some upsides) for Metacp, Metai and Metap. Evaluating the effects on Metac is non-trivial, but I'm willing to concede that one without further discussion.

**Comment by olafurpg** [comment]
Fixed in #1738. I am happy with keeping `Throwable` in metacp, metai and metap as long as metac uses `NonFatal`. I don't want to catch `Throwable` in metac because that's the most end-user-facing integration and I think it's bad UX to catch OOM and other VM errors.
