### ISSUE TITLE
Consider alternative name for s.Tree

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#1754]
This doesn't play well with m.Tree, which is a problem for Scalafix, since Scalafix doesn't have a luxury to get imported via a renaming import.

**Comment by maxov** [comment]
@olafurpg That sounds good to me!

**Comment by xeno-by** [comment]
Let me sleep on this and get back to you guys.

**Comment by olafurpg** [comment]
I just realized I have the same problem for scalafix.v1.Type, it conflicts with scala.meta.Type 😢 Looks like I need to come up with a different name there.

**Comment by olafurpg** [comment]
After more consideration, I went with `v1.SType` and v1.STree` instead of renaming the protobuf schema. The "S" prefix can be interpreted as "Scalafix" or "SemanticDB". Either way, this avoids ambiguous references with `import scala.meta._, scalafix.v1._` without changing the semanticdb schema or introducing difficult-to-pronounce names like "Tpt" or "Tpe".

Closing as wontfix.
