### ISSUE TITLE
Possible right-associativity of operator should be handled

### ISSUE THREAD

**Issue by Dveim** [scalameta/scalameta#192]
At the moment, right-associative operators are processed as left-associative ones.
```
scala> q"x*y".show[Structure]
res4: String = Term.ApplyInfix(Term.Name("x"), Term.Name("*"), Nil, List(Term.Name("y")))

scala> q"x::y".show[Structure]
res5: String = Term.ApplyInfix(Term.Name("x"), Term.Name("::"), Nil, List(Term.Name("y")))
```

**Comment by xeno-by** [comment]
This is actually okay, since we have a dedicated syntactic form for infix applications (`ApplyInfix`), and there we can discern left- and right-associative operators (just by looking at the name). If we desugared everything to to regular method applications (`Apply`), like in scala.reflect, then we would have problems when trying to match things like `x :: xs` with patterns like `$a $b $c`.
