### ISSUE TITLE
Add dialect to parse toplevel statements and packages

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1940]
Currently, when using the default dialect it's not possible to include toplevel statements
```scala
// Foo.scala
def foo() = 42 // error: expected class or package
```
With the `Sbt1` dialect, it's possible to parse toplevel statements but it's not valid to declare packages
```scala
// build.sbt
package bar // error:
```

It would be nice to have a third dialect that accepts both package declarations and toplevel statements. This dialect would be useful for example for Scalafmt, where we just want to format as much code as possible.

**Comment by adampauls** [comment]
I would like to resurrect this issue. The Scala3 dialect has allowTopLevelTerms, but it forbids package statements ( see [here](https://github.com/scalameta/scalameta/blob/main/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L5088). I'm assuming this is because `allowToplevelTerms` is used for the REPL, where package statements don't make sense, but it still seems curious not to allow the user some flexibility here.

**Comment by tgodzik** [comment]
It should be possible to change split this, since there is only one place this is being used:

https://github.com/scalameta/scalameta/blob/dc7320df79bb9ee8626281154fc36e8cb9cbc5cd/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L5088

I think it would be enough to add an additional dialect option and change to it in the code above. I don't have time to look at it currently, but I think we should be ok to merge this change.
