### ISSUE TITLE
Image links on website https://scalameta.org/ are broken

### ISSUE THREAD

**Issue by toddobryan** [scalameta/scalameta#1984]
It looks like all of them.

**Comment by iepsen** [comment]
Was about to open this issue as well 😄

**Comment by kpbochenek** [comment]
This is related to commit: https://github.com/scalameta/scalameta/commit/aa599eb73fc2f4a6d272d2f842512e74ae99d7cf

In `./docs/assets` there are files:
`astexplorer.png  established.png  foobar.png  foobar.png.gz  semantic-api.png  syntactic-api.png  tree.svg`

Out of them only `tree.svg` is correct. Rest is invalid because of:

`Fatal error reading PNG image file: PNG file corrupted by ASCII conversion`

Those 2 are not used and can be removed: `foobar.png  foobar.png.gz`

That leaves us with 3 image files that can potentially be taken from here if they are not outdated: https://olafurpg.github.io/scalameta/

https://olafurpg.github.io/scalameta/docs/assets/syntactic-api.png
https://olafurpg.github.io/scalameta/docs/assets/semantic-api.png
https://olafurpg.github.io/scalameta/docs/assets/established.png

@olafurpg ^^

**Comment by olafurpg** [comment]
Thank you for reporting! I opened https://github.com/scalameta/scalameta/pull/1989 to fix the broken images and also updated the downloads chart to the latest 12 months so it looks like this

![established](https://user-images.githubusercontent.com/1408093/74602701-97821f00-50a3-11ea-9f23-7ebbec8758d3.png)

**Comment by olafurpg** [comment]
The culprit was a `* eol=lf` line in `.gitattributes` that edited the PNG files
