### ISSUE TITLE
Add support for advanced ellipses in quasiquotes

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#234]
I mean things like `..($mods def $names = $bodies)`. This would require a major rethinking of unquote support in the parser, because currently things are very much hardcoded to expect Unquote tokens right after Ellipsis tokens.

**Comment by jvican** [comment]
I would love to have this.

**Comment by olafurpg** [comment]
How exactly would `..($mods def $names = $bodies)` work?

I'm personally against advanced ellipses when they are not self-explanatory and will maybe only be useful to <1% of users. We already have the full expressive power of Scala to compose scala.meta trees.

**Comment by jvican** [comment]
In my view, `..($mods def $names = $bodies)` will get all the method definitions (or even declarations) from any template, regardless of how many there are. Instead of manually pattern matching on a `Template` structure, the ellipsis is a rather elegant and less boilerplate-y solution. Based on my experience, this lack has arisen in almost any macro project I've worked on. Perhaps other metaprogrammers have always stumbled upon this. In all my cases, it has happened when analysing code whose structure is not clear upfront.

**Comment by olafurpg** [comment]
In the apply case, I thought that `..($mods def $names = $bodies)` would create a `Seq[Defn.Def]` from

```
mods: Seq[Mod]
names: Seq[Term.Name]
bodies: Seq[Term]
```

If I understand you correctly, in the unapply case, you could achieve the same thing with

```
// include nested defs
template.collect {
  case q"..$mods def $name =$body" => ???
}

// only top-level stats
template.stats.getOrElse(Nil).collect {
  case q" ..." =>
}
```

With this approach, you save yourself the effort of zipping the mods/names/bodies seqs.

**Comment by xeno-by** [comment]
> @olafurpg: I'm personally against advanced ellipses when they are not self-explanatory and will maybe only be useful to <1% of users. We already have the full expressive power of Scala to compose scala.meta trees.

I'm going to concur. We've been dreaming about advanced ellipses for almost five years now, but they just don't come up sufficiently often to warrant "a major rethinking of unquote support in the parser".
