### ISSUE TITLE
Model extension methods in semanticdb

### ISSUE THREAD

**Issue by tgodzik** [scalameta/scalameta#2443]
Scala 3 introduced extension methods which can be defined as:
```scala
package example

object O:
  extension (s: String)
    def method1(param : Int) = s * param
    def method2(param: Int) = s.take(param)
```
and currently this will be modeled as separate methods, which from semanticdb standpoint does not make sense since `s` extension param will shown as separate symbol in each of those methods.

We will have `example/O.method1().(s)` and `example/O.method2().(s)`.

Should we instead have a new logic to represent extension types?

I would suggest something like:
- `s` -> `example/O@String.(s)`
- `method1` -> `example/O@String.method1()`
- `param` in `method1` ->  `example/O@String.method1().(param)`
- `method2` -> `example/O@String.method2()`
-  `param` in `method2` ->  `example/O@String.method2().(param)`

Any other ideas? Does it make sense?

**Comment by tgodzik** [comment]
CC @olafurpg @tanishiking

**Comment by olafurpg** [comment]
The syntax “O@String” is problematic because you can’t encode the type “String” in the symbol, for the same reason we don’t encode types of parameters in method disambiguators. The reason is that you need a stable syntax that you can generate from 1) symbols on the classpath and 2) source code alone without a classpath. 

Do classpath symbols distinguish between the following cases?

* single extension group with two methods 
* two extension groups with a single method each 

Ideally I’d like to go with a syntax like “O.extension1@(s).”, “O.extension2@(s).”

**Comment by tgodzik** [comment]
> The syntax “O@String” is problematic because you can’t encode the type “String” in the symbol, for the same reason we don’t encode types of parameters in method disambiguators. The reason is that you need a stable syntax that you can generate from 1) symbols on the classpath and 2) source code alone without a classpath.

I haven't thought about that! I was too focused on a simple example.

> Do classpath symbols distinguish between the following cases

I don't think so, it actually just translates the extension methods to normal methods with some additional flags.

> Ideally I’d like to go with a syntax like “O.extension1@(s).”, “O.extension2@(s).”

This looks much better, maybe we could modify it a bit to have something similar to methods actually:
“O.extension@()(s).”, “O.extension@(1)(s).”
?

**Comment by tanishiking** [comment]
Let me clarify the issue: the problem with assigning multiple symbols to `s` in the extension group is https://github.com/scalameta/metals/issues/2627, and we should assign only one symbol to `s.`

> Ideally I’d like to go with a syntax like “O.extension1@(s).”, “O.extension2@(s).”
> This looks much better, maybe we could modify it a bit to have something similar to methods actually:
> “O.extension@()(s).”, “O.extension@(1)(s).” ?

I like this design `O.extension@()(s)., O.extension@(+1)(s).` which is consistent with the Disambiguator for the overloaded methods. https://scalameta.org/docs/semanticdb/specification.html#symbol-2

The potential issue with this would be we have to always increment the disambiguator every time we see the extension method, but I guess it's not a big problem.

**Comment by tanishiking** [comment]
Half a year later, I got a second thought.

Instead of modeling a new symbol descriptor for the extension method, is it an option to treat those symbols (extension parameter, e.g., `s`) as an alias?

For example in the example below,
```scala
extension (s: String)
  def foo: Int = 42
  def #*# (i: Int): (String, Int) = (s, I)
```
https://github.com/lampepfl/dotty/blob/90766d42e33bbc84be8b08c2df7811c2fe3d0dc9/tests/semanticdb/expect/Extension.scala#L3-L5

We have two symbol descriptors for `s` with the same range.
```
[2:11..2:12): s <- ext/Extension$package.foo().(s)
[2:11..2:12): s <- ext/Extension$package.`#*#`().(s)
```
https://github.com/lampepfl/dotty/blob/90766d42e33bbc84be8b08c2df7811c2fe3d0dc9/tests/semanticdb/metac.expect#L1310-L1311

Can we treat `ext/Extension$package.foo().(s)` and `ext/Extension$package.`#*#`().(s)` as alias? (because both of them have same range).

Or maybe we can add something like the `Aliases` section to `TextDocument` with

```scala
message Alias {
  repeated string symbols = 1;
}

message TextDocument {
  reserved 4, 8, 9;
  // ...
  repeated Synthetic synthetics = 12;
  repeated Alias aliases = 13;
}
```
?

And Scala3 compiler will be able to produce alias information more stable way (than their positional information).

---

My concerns about adding new descriptor syntax for extension methods are:

- It is too specific to Scala3
  - I'm not sure we'll use this descriptor syntax in other programming languages than Scala3.
  - I believe the philosophy of SeamnticDB design is trying to be language-agnostic, and adding a (relatively) language-specific model to spec is negative.
- It may end up distorting the "real" (symbol information given by a compiler) for the tooling side's convenience?
  - In the Scala3 compiler, `s` of `foo` and `#*#` have different symbols (am I right?). Tweaking those different symbols to be the same so that tooling features can work seems ... too much.

What do you think about it? @tgodzik @olafurpg 
FYI @bishabosha I'm interested in the opinion of someone who is proficient at Scala3 internal.

**Comment by olafurpg** [comment]
Just some rough thoughts. The most important criteria is that “find references” and “rename symbol” work with extension parameters. If you encode these as separate symbols then you want some way to identify the other symbols. Since these symbols are effectively local (you can’t reference them as named arguments from external files) then it’s less concerning that these are we stable identifiers. I wouldn’t worry too much about being language agnostic. SemanticDB already encodes a lot of Scala specific features and that’s fine, we’re still using it a lot at Sourcegraph to build language agnostic tooling :)

**Comment by bishabosha** [comment]
I would not approve the alias proposal for the extension parameter, syntactically they are defined in the same place, but they are unique symbols, one per each method

**Comment by olafurpg** [comment]
You can draw a parallel with case class constructor parameters that generate multiple different global symbols (copy param, apply param, constructor param, val getter). As long as there is a way to find out that these different symbols are defined together then it’s fine to encode them as different symbols.

**Comment by olafurpg** [comment]
> I like this design `O.extension@()(s)., O.extension@(+1)(s).` which is consistent with the Disambiguator for the overloaded methods.

This is my personal favorite at the moment. Stability is not a concern since these are effectively local symbols. I like treating these as the same symbol because it appears like a single symbol at the syntax level (find references and rename symbol treats it as a single symbol). For case classes, we can’t treat these as the same symbol because the constructor/apply/copy symbols are global (external files can reference those symbols via named arguments)

**Comment by tanishiking** [comment]
@olafurpg @bishabosha Thank you for your comments! I'm convinced to go with the original plan 👍 
> I like this design O.extension@()(s)., O.extension@(+1)(s). which is consistent with the Disambiguator for the overloaded methods.

---

> these symbols are effectively local (you can’t reference them as named arguments from external files)

Ah, that's right, I was too focusing on intra-textdocument cases.

> Collective extension method blocks should really be considered pure syntactic sugar for individual extension methods, rather than as a new construct

That makes sense, when I see the `extension` as pure syntax sugar, it's natural for me to generate a same symbol  :+1:

**Comment by bishabosha** [comment]
> Stability is not a concern since these are effectively local symbols. I like treating these as the same symbol because it appears like a single symbol at the syntax level (find references and rename symbol treats it as a single symbol). For case classes, we can’t treat these as the same symbol because the constructor/apply/copy symbols are global (external files can reference those symbols via named arguments)

I'm unsure what the meaning of this is, you can call an extension method like a normal method, in which case you can name the argument:
```scala
O.method1(s = "hi")(param = 23)
```

**Comment by olafurpg** [comment]
@bishabosha i assumed that was an error. That weakens slightly the arguments in favor of treating these as one symbol because you need to be able to compute the unified symbol from a call site of an external file/project.

**Comment by tgodzik** [comment]
I am starting to get the feeling that this is something that we need to handle on the Metals side in references :/

There are too many doubts about either approach. We could deduce in Metals that if a definition reference is at the same place as another symbol then it's an extension param and gather all definitions in the same place.

**Comment by tanishiking** [comment]
Thank you so much for all the discussions!

> I am starting to get the feeling that this is something that we need to handle on the Metals side in references :/

I kinda agree with @tgodzik , let's deal with the extension parameter on the tooling (metals) side :)

**Comment by tanishiking** [comment]
Closing this issue as we decided to deal with the extension parameters on consumer-side (e.g. Metals), and it is working well.
Thank you so much everyone who commented on this!
