### ISSUE TITLE
Typed quasiquotes

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#249]
@jrudolph has convinced me that we should give `reify` the second chance. Indeed, it is sometimes useful to write a quasiquote and have the compiler typecheck it statically. Even though it is my belief that statically typechecked quasiquotes constitute a minority of use cases for quasiquotes, they are still worth exploring.

Off the top of my head, my personal concerns regarding reify are as follows (would also be interested in hearing @densh's opinion):
1. Syntactic inconsistency with quasiquotes (I don't like having multiple ways of doing the same thing).
2. Necessity to introduce statically typed `Term[T]` which is incompatible with dynamically typed `Term`. Apart from being syntactically heavyweight (which is arguably justified by added safety), this complicates user experience and almost inevitably leads to code duplication.

If we have a proposal that avoids or alleviates these problems to acceptable levels, I'd be more than willing to consider it for inclusion in scala.meta.

**Comment by densh** [comment]
Even the simplest unquoting would require deep shapeless-grade type-level magic. For example something as simple as unquote splicing would require `HList`s. While this might be an interesting research question how much you can encode in types I think that time and complexity budgets are better spent elsewhere.

**Comment by jrudolph** [comment]
Thanks, @xeno-by, for having this discussion (even if it doesn't end up in any actionable task or solution).

Let's start from the reasoning why I think this is useful. 

With macros you have several stages of type-checking:

 - (1) macro code is compiled
 - (2) user code is compiled applying the macro
 - (3) user code is run

The goal is to report potential errors as soon as possible. E.g. as long as you don't use asInstanceOf you will be quite sure that you don't get any ClassCastExceptions during runtime (3) because any type mismatches will be caught by the typechecker at (2).

Now, what happens if there's a bug in your code generation code (1) and you write it only with quasiquotes. As trees are not yet evaluated (or type-checked) before macro expansion, you can only be sure that the trees are well-formed in a syntactical sense. (If you construct trees manually, you probably cannot be even sure of that.) Effectively, this means that some bugs in a macro implementation will probably only found at (2) when the expanded code is type-checked.

This is different with `reify` where you can be quite sure that any trees you generate will (most likely?) type-check at (2) because the construction of trees itself already guarantees that the generated expression will be well-formed and well-typed.

I think there's little to argue about that. The common objection seems to be that the range of programs you can generate using reify is so small that it isn't relevant, especially compared to the effort needed to make it work.

One reason is that the current reify implementation is severely crippled by the layering restriction which seems to be mostly an implementation detail.

My claim is that both holds:
 * most useful macros cannot be expressed using reify alone
 * however, many macros contain a part that generates code which only (or mostly) references symbols  that are already known during macro compilation which from benefit from reify

So, even if you cannot live with reify alone, IMO it makes sense to structure your macro code in a way that separates the hairy "dynamic" code (which can only be type-checked at (2)) from the safe code generation part which can be written with reify and which will already be type-checked at (1).

As evidence I can provide a current version of my experimental "speed" library which uses a custom version of reify that removes the implementation restriction that prevents nested reify/splice  expressions. Obviously, the library is quite code generation heavy, so that big parts of it, can actually be written using reify. For example, see the generation of terminal operations:

https://github.com/jrudolph/speed/blob/w/use-reify/speed/src/main/scala/speed/impl/TerminalGeneration.scala#L53

The `.reified` construct is what I introduced for nested reification. Regular nesting of `reify` wouldn't work in those cases.

**Comment by jrudolph** [comment]
@densh, yes splicing is a problem. Interesting idea to support that with HLists. Funny, that you suggest it, because, thinking about it, that's exactly what I did in those ancient times (where you still had to invent your own HList syntax...) in a very related use-case:

https://github.com/jrudolph/bytecode/blob/master/src/main/scala/net/virtualvoid/bytecode/MethodInvocation.scala#L22

**Comment by densh** [comment]
> This is different with reify where you can be quite sure that any trees you generate will (most likely?) type-check at (2) because the construction of trees itself already guarantees that the generated expression will be well-formed and well-typed.

Unfortunately this is true if you use only `reify`. The moment you construct tree manually and wrap into the `Expr[T]` the guarantees are gone. Due to limited compositional power of `reify`, most macros in practice had to do that. And this situation was in fact is the worst of both worlds: you have to do all the bookkeeping and you don't get any guarantees back. This led to untyped quasiquotes which remove all of the bookkeeping overhead and expand the compositional power to express just about any tree possible.

**Comment by jrudolph** [comment]
Yes, using `Expr.apply` in a macro implementation is similar to using `asInstanceOf` in a user-level program (that e.g. uses reflection). In some cases, you cannot be sure and you cannot prevent that some errors need to be shown at (2) because they are dynamic in nature. Still, that doesn't say anything about the remaining class of errors that could have been prevented by writing the static part of the macro implementation with reify.

**Comment by xeno-by** [comment]
I'm closing this feature request, since it hasn't been in strong demand in almost two years.
