### ISSUE TITLE
Deprecated unapply methods for Term.Match and others

### ISSUE THREAD

**Issue by PawanKartikS** [scalameta/scalameta#3023]
Hi there!

I'm trying to bump up the scalameta from a very old version to the latest. As soon as I moved to `4.7.1`, I noticed some warnings that the `unapply` method is deprecated for `Term.Match`, `Term.Apply`, and a few others.
```scala
// Example flagged snippet
tree.traverse {
  case Term.Apply(Term.Name("myMethod"), _) => //
  case _ => //
}
```

I'm unable to find the relevant changelog. Could you help me point towards it? Normally, I'd have not created a new issue for this but looks like most tools such as ASTExplorer as stuck on old versions (yep, there's a PR open for the upgradation).

**Comment by kitbellew** [comment]
@PawanKartikS what is the question, exactly? are you trying to find release notes for recent versions of the library?

**Comment by PawanKartikS** [comment]
I'm trying to find out the versions in which these `unapply` methods have been deprecated. Is there any particular reason why this was done, and, what's the alternative? This will help me in migrating to the latest versions.

**Comment by kitbellew** [comment]
it was done in 4.7.0 because we had change the types of fields in some of these trees. for binary compatibility, we kept the original unapply definition but marked it deprecated (until 5.0.0).

the alternative is either
- not to use unapply at all (i.e., replace with `case x: Term.Apply if x.argClause.values .... =>`), or
- utilize something that carries no binary-compatibility guarantee: `case Term.Apply.internal.Impl(..., ...) =>`.

**Comment by PawanKartikS** [comment]
Perfect! Thank you so much.
