### ISSUE TITLE
Missing `index` method on token that returns index of token in root tree's `.tokens`

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#332]
I have a token and I want to know which index amongst all tokens that share the same root tree.

Use cases:

* in some method I have a single token and I want to know which token is next to it, if token is not BOF or EOF.
* I want more performant hashing since I don't care about collisions on tokens from separate trees. This trick
```scala
(token.privateTag << (62 - 8)) | (token.start << (62 - (8 + 28))) |token.end
```
1) is hacky
2) yields a long and hash keys should be ints and 
3) is limited by source file byte size instead of token count, which is much smaller.

**Comment by xeno-by** [comment]
I don't think we can have this, because tokens are modelled independently from trees. We can tokenize an input without ever parsing the result, so in that case `Token.index` wouldn't make sense in the formulation proposed in the title of this issue.

If we take another formulation, having `Token.index` be an index of a token in a tokenization of an input, we run into another problem. Even though, the public API can no longer create tokens, it is still possible to create ad-hoc collections of tokens, mixing tokens from different tokenizations. In such a mixed case, `Token.index` also doesn't make sense.

All in all, I'm inclined to close this issue, because introducing the proposed API runs into problems, as explained above, and the only use case (as far as I can see) that it would enable can already be worked around.
