### ISSUE TITLE
scalac compatibility for error messages

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#383]
This is something that we inherited from scalac. Since scalac runs in -Yrangepos only occasionally, its error reporting is offset-based. Therefore, all positions (both offset and range ones) have `Position.point` in scalac.

In our case, everything had range positions from the very beginning. Therefore, we should consider dropping `Position.point` altogether, in favor of Clang-style/Elm-style range errors.

**Comment by xeno-by** [comment]
In 7a193ed47638f6a6b3216814866ae95cc7b57344, I removed Position.point. See the commit message for justification. Let's see how this pans out.

**Comment by olafurpg** [comment]
For better or worse, it seems we need point in order to implement rewrites like RemoveUnusedImport in scalafix, see https://github.com/scalameta/scalameta/issues/839#issuecomment-300461870

I am working on a PR that adds a new Position.RangeWithPoint type which guarantees that start < point < end. In addition, this requires a change in the semanticdb.proto schema.

I propose that we then customize Position.Range.unapply to also work for RangeWithPoint. WDYT?

**Comment by xeno-by** [comment]
Recently, we decided to limit the surface of our work to actionable items only - either bugs in existing code or feature requests that are warranted by the roadmap. Since we've worked around the described issue in Scalafix, this ticket is neither, so I'm going to close it.
