### ISSUE TITLE
Enclose all optional-braces regions in a tree

### ISSUE THREAD

**Issue by kitbellew** [scalameta/scalameta#3913]
There are multiple cases of optional-braces regions described using `<<<` in https://dotty.epfl.ch/docs/internals/syntax.html.

Unlike actual-braces-delimited regions, there is currently no reliable way to capture which `Trivial` (aka, `Comment` or `Whitespace`) tokens belong to each such region, which makes it very difficult, sometimes impossible to format comments.

Therefore, let's enclose all such regions which are currently described as `List[...]`.

**Comment by bjaglin** [comment]
One of the added indirection (`Tempate.body`) had caused regression in one built-in scalafix rule because `tree.parent` changed. Fix was [easy](https://github.com/scalacenter/scalafix/pull/2079/files#diff-705caec25d81b1cd03a3378d1b6fc048177a812843eee5fd7042e98219a16535), but I wonder if this change and other ones added for this issue are not enough to call for a 4.10.0?

**Comment by kitbellew** [comment]
@bjaglin released

@tgodzik i can't figure out: is this build failing (first run definitely was marked red): https://github.com/scalameta/scalameta/actions/runs/11003723347/job/30554001637
