### ISSUE TITLE
IntelliJ: cannot resolve symbol Token

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#394]
With the large overhaul of Tokens, this started popping up in some random places

![screen shot 2016-05-11 at 17 56 28](https://cloud.githubusercontent.com/assets/1408093/15187563/cefa4780-17a1-11e6-8419-85dc663e4359.png)

It's not everywhere, here is another case in the same Term.Match that resolves fine:

![screen shot 2016-05-11 at 17 58 23](https://cloud.githubusercontent.com/assets/1408093/15187605/f9e21324-17a1-11e6-831b-cc8fe07e8317.png)

I `import scala.meta.tokens.Token._` at the top of the file.

IDE support is critical for dummies like me :)

BTW, it works fine if I refactor the former statement into this:

```scala
      // Case
      case tok @ FormatToken(_, _: KwMatch, _) =>
        Seq(
            Split(Space, 0)
        )
```

**Comment by xeno-by** [comment]
This seems to happen due to the fact that KwMatch (and other tokens) are generated by a macro annotation: https://github.com/scalameta/scalameta/blob/master/scalameta/tokens/src/main/scala/scala/meta/tokens/Token.scala#L47. 

@Alefas @mutcianm How do I make Intellij understand what macro annotations like @ast, @token, etc do? I remember there was an experimental technology to do that. What's its current status? Is there a tutorial that would explain how to use it?

**Comment by mutcianm** [comment]
Expansion spoofing feature currently is limited to manual in-place macro expansion - more of a macros developer assistant.
It's rather easy. Simply press `Alt+Crtl+Shift+Z` with caret placed on the line with macro annotation(or any other statement which expands as a macro) and it will expand in-place.

**Comment by xeno-by** [comment]
@mutcianm I was wondering about something a bit different. The problem that we're discussing here stems from the fact that we have a class `KwMatch` in scope, and the macro annotation puts a companion object next to it. Intellij seems to not see the companion object, so it displays red squiggles. How do we avoid the spurious error?

**Comment by olafurpg** [comment]
The nightly Scala Plugin for 2016.3 EAP shows no false warnings for my usage of scala.meta.
