### ISSUE TITLE
parse error in scalafix

### ISSUE THREAD

**Issue by gfrison** [scalameta/scalameta#4086]
scala version: 3.6.2
scalafix version: 0.13.0
```
error: `]` expected but `:` found
[error]   type Jf[F[*] <: FunExpr[*]]    = [T:Show] => (F[T], Null) => Juro[T]
[error]                                      ^
```

I get an error on [T:Show] which compiles correctly

**Comment by kitbellew** [comment]
@gfrison can you please modify this into a properly reproducible submission, or close? you don't show the code, nor the error, nor do you use scalameta to parse it. if the error is in scalafix, please move it to the scalafix repository.

**Comment by tgodzik** [comment]
Och, actually this looks like it would fail in Scala 2, but should work in Scala 3 parsing

The full snippet here is enough.
`type Jf[F[*] <: FunExpr[*]]    = [T:Show] => (F[T], Null) => Juro[T]`

I suggested that @gfrison opens an issue here since it looks like an actual bug, but this might be some issue with scalafix config actually.

**Comment by kitbellew** [comment]
> Och, actually this looks like it would fail in Scala 2, but should work in Scala 3 parsing

@tgodzik ah, well, this is not valid scala2 code, and scalameta has no problem with it using scala3. 

> The full snippet here is enough. `type Jf[F[*] <: FunExpr[*]] = [T:Show] => (F[T], Null) => Juro[T]`

i understand that, but the code is not always sufficient. dialect, errors etc. are important telltale signs for triage, and avoiding wasting cycles on wild-goose chases.

**Comment by tgodzik** [comment]
Yeah, you're right I think in this case is another issue
