### ISSUE TITLE
scalameta-contrib

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#537]
The scala.meta trees and tokens APIs can be a bit low-level sometimes. It would be nice to have a library with utility methods for common operations, for example

- `trailingComments`/`leadingComments` on tree nodes, see https://gist.github.com/olafurpg/7be8f1d5aa9d01853e9ce514838710cc#gistcomment-1803194
- `Whitespace`/`Keyword`/... token extractors, see https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/util/TokenClasses.scala
- tree extractors classes: https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/util/TreeClasses.scala
- `toType/toPat/toTerm` from `Term.Name/Pat.Var.Term/Type.Name`
- `def parents(tree: Tree): List[Tree]` for all parents of a tree
- `Patch` to do high-performance token level transformations, something like an optimized and safer variant of https://github.com/scalacenter/scalafix/blob/master/core/src/main/scala/scalafix/util/Patch.scala
- pretty print hack: https://gist.github.com/olafurpg/00ce1601a7e213141f25
- maybe something from scalafmt TreeOps/TokenOps 

I'm sure there's a ton of other useful ideas that could be bundled into this library.
Would anyone be interested in using/contributing to such a module?

cc/ @ShaneDelmore

**Comment by ShaneDelmore** [comment]
I haven't worked with it enough to have a ton of good ideas yet but brainstorming for a few minutes I come up with this:

On high performance patches, Is this backed by a mutable or immutable array?  Would we save allocations by having multiple types of patches:  Say Add | Remove | Replace.  Replace could be only same sized replacement so no need to shrink or grow the array.  Add/Remove could possibly be stacked in such a way that multiples could be stacked say an Add and Remove both of same length squashed into a Replace?

Due to the nature of syntax wrapping and unwrapping is more common than the usual collections API, more Ops working on both ends of the stream at once could be really useful.  I posed a couple of small examples to https://gist.github.com/ShaneDelmore/50bee845755d8cf81946ee2fff3efe9e

Examples;

def takeOuter(n: Int) = (take(n), takeRight(n))

def takeOuterWhile(forwardPredicate, reversePredicate): (Tokens, Tokens)
  This is basically some concept of the fact that some tokens are related, like LeftBrace and RightBrace.  It would be handy to be able to have an matchingBraces predicate that matches LeftBrace when starting at the front of a Seq[Token] and matches RightBrace when start at the end  of a Seq[Token]

Tuple2(A, A) map, forEach, toSeq[A]

Do we need Ranges at times to references segments of tokens where we only care about start and stop but not the actual contents?  I am not familar enough with Patches to know if the old value was important or if we just need to know where to start and stop.

flatMap/flatCollect would be great to minimize ifs.

**Comment by DavidDudson** [comment]
Sounds like a great idea. I can definitely help. A lot of the ideas behind Elysium require Mod.Inline support so I'll hopefully get back into meta soon

**Comment by olafurpg** [comment]
@ShaneDelmore Regarding the patch, I had imagined the API would be something like

```scala
sealed abstract class Patch
object Patch {
  case class Remove(tokens: Seq[Token]) extends Patch
  case class Add(at: Token, toAdd: Seq[String]) extends Patch
  case class Replace(from: Token, to: Token, toReplace: String) extends Patch
}
def patch(input: Tokens, patches: Seq[Patch]): String
```
 
Regarding performance, I imagine it should be possible to implement the method with a single pass on the input and build the result in a StringBuilder. We might also need to sort the patches. It does not have to be ultra-optimized, it's fine as long as it only does a single pass on the input. My referenced solution allocates a new Seq[Token] for each patch, which is terribly inefficient. 

Regarding safety, the implementation should take care of conflicts between patches.

> takeOuter

I am a bit sceptical about the utility of that method. You have little guarantees that each side corresponds to each other. For example, `"function(a, b)".tokenize.get.takeOuter(1)`. I think it might be more useful to have utilities to deal with matching paren/brace/bracker. See here: https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/util/TreeOps.scala#L130. If you have an opening paren and want to get the closing paren, you could look it up in that map.

> flatMap/flatCollect

Great idea! I do flatten on the result of `collect` all the time.

**Comment by ShaneDelmore** [comment]
In my example I believe I have takeBalancedOuter which takes equal length (Nil, Nil) in your example but I thought maybe people would want take outer when doing things like taking all whitespace on both sides of a statement.  That may be already well handled though.

**Comment by ShaneDelmore** [comment]
I envisioned maybe you would do a lot of things like wrap expressions, for example a debug annotation that wrapped an expression, in a new function that logs it's output, then passes it on.  If that is not an actual common use case then takeOuter is probably going overboard.

**Comment by ShaneDelmore** [comment]
Those TreeOps methods are great, thanks for pointing them out

**Comment by xeno-by** [comment]
Another candidate for inclusion into contrib: https://github.com/liufengyun/eden/commit/37fa37ae7847675edc244f2cd2fc7da925d6d82d#commitcomment-20128802

**Comment by olafurpg** [comment]
Here's another candidate for inclusion: https://gist.github.com/olafurpg/b9a2c8ca25ec71809e7f4d133ff1b70b

**Comment by DavidDudson** [comment]
Possibly another candidate, Although it would need some improvements first (It's only a prototype currently), I think we could almost merge this into paradise at some stage if that is wanted. I'm pretty sure the same technique could be used for Def macros also.

https://github.com/DavidDudson/Elysium/commit/db831a4d7bdaa2865daba9c1b3b89a044f098aad#diff-691567402960237bc1057a1324182780

**Comment by DavidDudson** [comment]
Would contrib be just another subproject in this repo (much like trees/prettyprinters etc?) or a separate repo? I would like to start working on this.

**Comment by xeno-by** [comment]
I suggest it being another subproject at `scalameta/contrib`.

**Comment by olafurpg** [comment]
I opened a PR to add a contrib module, https://github.com/scalameta/scalameta/pull/624

**Comment by DavidDudson** [comment]
What out of this is now missing? @olafurpg can we split out the missing items into specific issues and close this?

**Comment by olafurpg** [comment]
@DavidDudson We are safe to close this issue, I'm very happy to see `contrib` forming shape!
