### ISSUE TITLE
upgraded drone

### ISSUE THREAD

**Issue by fommil** [scalameta/scalameta#577]
sorry, I upgraded drone and it broke the old install.

Upgrading is easy, I've added @xeno-by as a user and you can enable this repo here http://ci.fommil.com/account

You then need to add your credentials using the new system, and upgrade your .drone.yml file. This boils down to:

0. delete the old webhook for fommil.com
0. wrap the `build:` section in a `pipeline:` (there might be other changes but I don't think they are relevant)
1. delete the .drone.sec
2. install the drone CLI http://readme.drone.io/0.5/install/cli/
3. set up the envvar token (which you can get from the server) and then type commands like this

```
drone secret add --image=ensime/ensime:* --skip-verify=true scalameta/scalameta SONATYPE_USERNAME xeno-by
drone secret add --image=ensime/ensime:* --skip-verify=true scalameta/scalameta SONATYPE_PASSWORD super_secret_password
```

any more questions, ask at discourse.drone.io

**Comment by fommil** [comment]
btw, if you leave out `-Dsbt.ivy.home=/drone/cache/ivy2` you will get a speed boost, because we have lots of artifacts cached already in the default location.

**Comment by fommil** [comment]
and also don't set `COURSIER_CACHE`

**Comment by xeno-by** [comment]
@fommil Thanks a lot for your continuous support!

After your drone installation has become broken, @olafurpg set up another drone server, and we've been successfully using it ever since. For the time being, Olaf's server works well, so I wouldn't want to  fix something that's not broken :)

I'll be closing this issue, but if something happens to our server, I'll know where to go for help.

**Comment by fommil** [comment]
cool! I'd be happy to rehost yours again and share resources if you need it. But if Olaf's server is the server I think it is, then you'd be mad to move away from it :-)
