### ISSUE TITLE
Enable Literal Types syntax for Scala 212 when version 2.12.3 is released

### ISSUE THREAD

**Issue by xavier-fernandez** [scalameta/scalameta#645]
The PR https://github.com/scalameta/scalameta/pull/640 is due to be merged, enabling Literal Types syntax on Dotty. 

In spite type literals are not yet available on Scala 2.12, it is scheduled [to have them supported by Scala 2.12.2](https://github.com/scala/scala/pull/5310). When Scala 2.12.2 is released, the Scala 2.12 dialect should enable the flag for supporting literal types: https://github.com/scalameta/scalameta/pull/640/files#L175

**Comment by xeno-by** [comment]
Also, we shouldn't forget to enable trailing commas as well.

**Comment by xeno-by** [comment]
Trailing commas are already enabled for `Scala212`. Only literal types are pending.

**Comment by xeno-by** [comment]
Literal types got delayed again: https://github.com/scala/scala/pull/5310#issuecomment-311830956. 

Given the evident uncertainty that surrounds planning of some of the advanced language features, I think it is best to close this issue (and issues like this one) and be reactive rather than proactive in accommodating language changes.
