### ISSUE TITLE
Support for runtime reflection

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#739]
In 1.6.0, we already have some means of runtime reflection via offline mirrors (https://github.com/scalameta/scalameta/issues/607) and more functionality is scheduled to arrive in https://github.com/scalameta/scalameta/issues/609 and https://github.com/scalameta/scalameta/issues/612. 

However, in addition to the API shared between compile-time and runtime reflection, it may be useful to also implement RTTI-based features such as `AnyRef.tpe`, analogues of manifests/type tags, etc.

**Comment by deaktator** [comment]
This may be the wrong ticket to discuss this, but I'm wondering how much of the current `scala.reflect.runtime` (and `scala.tools.reflect.ToolBox`) code will be in Scala.meta.  Will there be a notion of toolboxes in Scala.meta?

I have a library ([Aloha](https://github.com/eharmony/aloha)) that uses runtime code generation and on-the-fly compilation to turn *quasiquote-like* statements into functions that extract data from domain objects.  I started it in Scala 2.9.3 (before 2.10 was release) and it currently uses String-based code gen and Twitter util Eval for compilation.  So for instance, given the domain objects:

```scala
case class Another(opt_double: Option[Double])
case class Domain(another: Another, req_double: Double)
```

and a feature extraction specification (typically in a configuration file or JSON):

```scala
"pow(sin(${req_double}), 2) + pow(cos(${another.opt_double}), 2)"
```

Aloha generates a function like this (*Simplified here*):

```scala
class Fn extends (Domain => Option[Double]) {
  def apply(d: Domain): Option[Double] = {
    import scala.math.{cos, sin, pow}
    d.another.opt_double map (o => 
      pow(sin(d.req_double), 2) + pow(cos(o), 2)
    )
  }
}
```

Not happy with the string-based code gen, I created [SciFn](https://github.com/scifn/scifn) that uses Scala 2.10 / 2.11 `scala.reflect`.  It uses both macros and runtime reflection because I want to be able to specify features both inside Scala code (macros) and externalized in config files (Runtime reflection).  I tried to modularize the code so that it shares as much code as possible between macros and runtime reflection.  Below is an example for a specific domain type.

## [Runtime version](https://github.com/scifn/scifn/blob/master/scifn-gen/src/main/scala/scifn/gen/impl/ident/package.scala#L31-L34)

```scala
case class RuntimeIdentityFeatureGen[A](implicit val awtt: ru.WeakTypeTag[A])
   extends IdentityBasisCreator[A, ru.type]
      with FeatureGen[A, ru.type]
      with RuntimeFeatureGen[A]
```

## [Macro version](https://github.com/scifn/scifn/blob/master/scifn-gen/src/main/scala-2.11/scifn/gen/impl/ident/MacroIdentityFeatureGen.scala#L12-L17)

```scala
object MacroIdentityFeatureGen extends MacroCompanion[Any] {
  override protected[this] def instance[A : c.WeakTypeTag](c: blackbox.Context) =
    new MacroFeatureGen[A, c.type, c.universe.type](c)
      with FeatureGen[A, c.universe.type]
      with IdentityBasisCreator[A, c.universe.type]
}
```

Aloha still doesn't use SciFn because I am waiting to drop 2.10 support (b/c [SI-6240](https://issues.scala-lang.org/browse/SI-6240)).  I'm hoping that it would be possible rewrite SciFn using Scala.meta.   Obviously, I can do all of the parsing and AST manipulation with Scala.meta without this, but I'm wondering if there will be toolboxes or some mechanism for runtime compilation or should I just rely on some other mechanism JSR 223 [SI-874](https://issues.scala-lang.org/browse/SI-874), Twitter util Eval, or some other embedded compiler?

**Comment by xeno-by** [comment]
@deaktator Scala.meta API is designed to be agnostic of the execution environment. In fact, our core use case right now - loading and utilizing a semantic db (https://github.com/scalameta/scalameta/issues/605) outside a compiler - requires some support for runtime reflection.

That being said, we don't have an implementation for runtime compilation yet, and neither we have a roadmap entry for that. Would you be willing to contribute this feature? I know how to do this without `scala.reflect.runtime`, and it shouldn't be too hard.

**Comment by olafurpg** [comment]
I might be tempted to take a stab at runtime compilation to use in scalafix (see https://scalacenter.github.io/scalafix/#Customrewrites). Currently, we use toolbox but it has limitations such as it doesn't allow `Package` and causes issues like https://github.com/scalacenter/scalafix/issues/101

I can't promise a timeline, but I'll probably take a look sometime in April.

**Comment by deaktator** [comment]
Happy to take a look at it but I haven't looked too hard at the scala.meta code.

**Comment by xeno-by** [comment]
I'd say we could add `Mirror.eval(tree: Tree): Any` (or, if we decide to be especially pure, we could introduce a dedicated capability for that).

The implementation would likely be similar to `eval` in the scala.reflect toolbox (https://github.com/scala/scala/blob/1706a37eb84ec252aea77bccebad3e48448534ad/src/compiler/scala/tools/reflect/ToolBoxFactory.scala#L203). We'd also need some glue code to set up a scala.reflect environment and convert scala.meta trees to scala.reflect trees (see https://github.com/scalameta/scalameta/blob/master/scalahost/src/main/scala/scala/meta/internal/scalahost/v1/online/Mirror.scala#L74 for inspiration).

**Comment by xeno-by** [comment]
@olafurpg What do you think about this issue? Are you still interested in looking into it? I propose we drop it, because it doesn't align with the current feature requests that are nowadays centered around semantic db.

**Comment by deaktator** [comment]
@xeno-by If this issue is dropped, what do you think the long-term alternative will be going forward?  Do you imagine scalameta will supplant `scala.reflect.runtime`?  If it will, this feature seems pretty useful.  I think that if @olafurpg doesn't want to take this up, I would like to.  I am trying to figure out if I can get sponsorship or whether I'll have to work on it in my free time.  Could you please hold off on deleting this until late this afternoon so I can check if I can get some time to work on this?

**Comment by xeno-by** [comment]
Let's postpone the decision by several days. Please take your time to discuss this issue internally.

From how it looks at the moment, semanticdb will allow us to do some runtime reflection. Even though runtime reflection is not an explicit goal for the project, you can give Scalameta a classpath and get back Scala metadata for this classpath. There aren't any readily available APIs for that, but you'll be able to obtain a list of definitions in the project, their signatures, maybe even their members (this one will require a lot of work though).

However, object introspection (getClass, Field.get/set, Method.invoke, etc) and especially runtime compilation can't be implemented with semanticdb alone. They will require heavy custom development to the point where I'm not even sure whether we'd want to have this functionality in Scalameta (having something in Scalameta means that we'll need to support that something, and from where I stand I don't think this aligns with the core goals of the project at the moment).

At the moment, this is just my personal opinion. I'm willing to discuss and potentially commit to this functionality if convinced that this will be best for the project. @olafurpg, I need your input.

**Comment by olafurpg** [comment]
I personally think runtime reflection is outside the scope of scalameta with the direction we're taking in 2.0. None of our modules have a dependency on the compiler (except the semanticdb-scalac compiler plugin), so runtime reflection utilities would have to be separate artifact either way. It's still possible to use scalameta trees/quasiquotes for code-generation as a replacement of brittle string manipulation. I may at some point implement `(Sourcepath, Classpath) => Database` functionality for scalafix, but that would be very different from the functionality `scala.reflect.runtime` provides.

**Comment by tgodzik** [comment]
Recent work concentrated on the parser and semanticdb, so I think no one will be picking this up in a near future.
