### ISSUE TITLE
Semantic DB is not portable

### ISSUE THREAD

**Issue by stuhood** [scalameta/scalameta#777]
The semantic db currently stores absolute filenames: 
```
$ cat semanticdb
file:/Users/example-user/Projects/Meta1x/sandbox/Library.scala
[7..14): Library => _empty_.Library.
...
```
... which means that the db isn't portable across machines/directories.

Inferring or allowing for configuration of a "source root" or "sourcepath" at compile time for a particular compile unit would allow for relativizing these paths. One approach that I've seen before is to attempt to strip the package name from the source filename, and use the resulting directory as a root. But that won't be perfect, because scalac doesn't require that a source be located in a relevant package-named directory.

**Comment by olafurpg** [comment]
One alternative approach would be to include the source file contents in semanticdb. We can use `Input.LabeledString` for that https://github.com/scalameta/scalameta/blob/13087aafb7e9db4d8926740fb86578bdd494ad6b/scalameta/inputs/shared/src/main/scala/scala/meta/inputs/Input.scala#L50 The schema can accommodate this change https://github.com/scalameta/scalameta/blob/13087aafb7e9db4d8926740fb86578bdd494ad6b/scalameta/semantic/shared/src/main/protobuf/semanticdb.proto#L21-L22

Benefits to this approach
- solves portability
- semanticdb continues to work even if the file contents change on disk

Downsides
- bigger semanticdb file size, could be offset with compression
- ?

We might still want to make the paths relative in the `label` field.

**Comment by olafurpg** [comment]
Related https://github.com/scalameta/scalameta/pull/808#pullrequestreview-33947891 I would be interested to hear your opinion @stuhood on what do with `Anchor` and adding a `contents` field to `AttributedSource`

**Comment by stuhood** [comment]
@olafurpg : I don't really have an opinion on `Anchor` vs `Location` vs `Position`, as they all seem to be shaped approximately the same way, and I don't really know why they might have been split in the first place.

With regard to adding the complete contents of the file to the database: it seems more durable, and might make things easier in the context of build systems that don't have an accurate fingerprint to match a set of compile outputs (and thus `semanticdbs`) to a set of source files.

But I'm not sure it solves the problem of relativizing paths... for example, in the case of scalafix or scalafmt you might want to execute updates "in place", which means you need to be able to construct an absolute path to the output file, and correlate it to the contents of the database. This still feels like it ends up meaning that you need a root at "mirror use time" that matches the root from "compile time".

I recently wrote up a quick blurb about what pants does for relativization here: https://github.com/sbt/zinc/issues/218#issuecomment-294928412

**Comment by olafurpg** [comment]
@stuhood Interesting. I agree that the problems of 1) relativizing paths and 2) including source contents in the semanticdb are orthogonal issues. 

I think that adding a "source root" field to the [`Database` message](https://github.com/scalameta/scalameta/blob/cb5dd112079b37cb3d874a337230cfde25682847/scalameta/semantic/shared/src/main/protobuf/semanticdb.proto#L6) is a good solution to 1). That should be enough to solve the problem in sbt. I'm not sure `baseDirectory.value` is stable enough in sbt to be used as a source roo, since some multi-module builds can be started in sbt from separate base directories. However, I think a per-project `sourceDirectory.value` should do the trick.

As for 2), I think a good solution would be to support both "slim" semanticdb using `Input.File` without file contents and "fat" semanticdb using `Input.LabeledString` that includes file contents (names are open). For example, if I want to build a static site generator like https://github.com/sbt/sxr with interactive search based on Scala.js I may want to use the "fat" option since the file paths cannot be read in the browser.

The schema already has support for both options, see here https://github.com/scalameta/scalameta/blob/cb5dd112079b37cb3d874a337230cfde25682847/scalameta/semantic/shared/src/main/protobuf/semanticdb.proto#L21-L22 we could use the convention that if both path + content is set then Input.LabeledString is used. Then scalahost-nsc could read from -Dscalahost.semanticdb.output=fat/slim to choose which strategy to use when generating the semanticdb.

@xeno-by this is very relevant for #808

**Comment by stuhood** [comment]
> I think that adding a "source root" field to the Database message is a good solution to 1).

I'm pretty sure that goes back to the root issue with the ticket: the database would contain an absolute path, and thus wouldn't be portable.

Now, on the other hand, if the sourceroot value was a required option at both compile and mirror-use time, I expect that it would work fine.

**Comment by xeno-by** [comment]
@olafurpg, thanks a lot for writing down your proposal. This is what I was aiming to achieve in Chicago, but I ultimately backed down because I didn't have time to flesh out the details.

upd. I'll finish this comment later today or tomorrow. I have something that I believe is quite elegant, but still needs refinement.
