### ISSUE TITLE
Monads vs exceptions for error handling

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#821]
This is a long-standing debate between @densh (monads) and myself (exceptions). Some time ago, @olafurpg joined the fun on Denys's side.

The debate basically boils down to: "for which APIs do we represent errors in type signatures?". A related question is: "if we use types, then which ones?".

**Comment by DavidDudson** [comment]
My opinion is all should use Monads.

I quite like macro failures throwing exceptions, but only because it's compile time only.

Do we have a list of Api's and what exceptions the can throw?

**Comment by xeno-by** [comment]
The immediate motivation for filing this ticket is the discussion in https://github.com/scalameta/scalameta/pull/808. 

As mentioned in one of the reviews of the pull request, invoking `AbsolutePath.apply(path: String)` can result in an error if `path` is not absolute. How do we represent this error?

In the pull request, I specified the return type as plain `AbsolutePath` and then had the body of `apply` to throw `sys.error` if the argument is invalid. Below you can find my motivation.

1) When deciding between monads and exceptions, I typically ask myself a question: "can future callers of a given API reasonably handle the error?". If the answer is "no", then I use exceptions. 

For example, I wouldn't expect anyone except for hardcode VM/framework programmers to handle things like NPE and SO, so I don't express those erroneous conditions in signatures.

2) If it is imaginable for the error to be handled, I ask myself another question: "are API users likely to want to handle the error?". If the answer is "not really", then I use exceptions. 

For example, let's take `Mirror.apply(classpath, sourcepath)` that is supposed to be the foundation of adhoc semantic API. It clearly can fail, because the underlying semanticdb may be corrupt, may be in an incompatible format, etc. So should it return `Mirror` or `Try[Mirror]`?

I think that `Mirror.apply` should return `Mirror`, because I can hardly imagine API users wanting to handle the aforementioned errors.

If the semanticdb is corrupt, what is a user likely to do? Sure, sometimes they may want to take this error and convert it into something domain-specific, but which use case is going to be more often: 1) the happy `implicit val mirror = Mirror(...)`, or 2) the overly cautious `implicit val mirror = Mirror(...).orElse(...)`? I think that 1 is much more frequent, so I believe we should optimize the API towards that.

3) Otherwise, I guess it may make sense to use monads if the end result is not too heavyweight.

In particular, I'm interested in the following experiment. After #808 is merged (and that'll happen really soon), it would be interesting to see what happens if we change all `AbsolutePath.apply` and `RelativePath.apply` methods to return `Option[...Path]` instead of `...Path`. What kind of diff we'll end up with?

**Comment by xeno-by** [comment]
@DavidDudson I don't know of such a list. We do explore our API surface in https://github.com/scalameta/scalameta/blob/master/scalameta/scalameta/jvm/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala, but not to that extent. It would be an interesting exercise to pursue.

**Comment by DavidDudson** [comment]
@xeno-by I do like your reasoning, but here's my take. 

Exception types:
- SO/OOM are almost always fatal errors, no one should ever try and catch them (Unless they really know what their doing)

- NPE should never be thrown in the first place, having a value possibly `null` anywhere seems like a red flag to me, one that idiomatic Scala avoids. So you should never have to catch it. (Options/Either/Try as alternatives)

One time use tools (eg. running scalafix):
- Probably wouldn't care about exception throwing
- The user of these tools should be able to fix the error and rerun the tool.

Constant use tools (IDE's/chat bots etc.)
- Will need to recover from errors. 
- I presume most Scala devs do not check Scaladocs to make sure methods don't return any exceptions. This is largely because Scala does not have checked exceptions, and also because the more experienced users expect the type signature to show this information.

I think users of scalameta are fairly intermediate/advanced Scala devs to begin with so monadic style is not going to be a completely alien concept to a majority of the users.

Api level:

- If there are only a few places where exceptions can be thrown (such as `Mirror` creation) I am fine with exceptions being thrown.

- If a large amount of method calls call throw an exception, we should consider monadic style.
  - Monadic by default: `implicit val mirror = Mirror(...).orElse(...)` 
  - Exception throwing => Monadic: `implicit val mirror = Try(Mirror(...)).orElse(...)`
  - Both are not actually that different in this case.
  - The downside is that the user has to know that the should wrap the call in `Try` which means the number of different areas in the code that actually throw exceptions matters (As it is all cognitive load remembering what does and doesn't throw)
  - If the entire api tells you what errors can happen (Through types) then the user can feel safe knowing that at runtime, an exception will not be raised (Unless it's fatal)

**Comment by olafurpg** [comment]
The root of this discussion is really about exceptions vs. "document errors in
the type" for error handling.  Monad has a very specific meaning, I prefer not
to get into that discussion.

There is no silver bullet for error handling. Sometimes you want
- end the world/fatal: exceptions
- fail on first error:
  - No message: Option[T]
  - Custom message: Either[Msg, T]
  - Don't know exact type of error message but error is likely: Try[T]
    (PS. Try[T] is essentially Either[NonFatal, T] with nicer syntax).
- error accumulation: something applicative like Validation[NonEmptyList[Msg], T]

As @DavidDudson points out, Scala has no checked exceptions (thank god IMO) and
that means we need to be more diligent than in Java to document errors in the
return type.  Exceptions should be left for truly **exceptional**
situations/errors like StackOverflowException or InvariantFailedException in Tree (exceptional because quasiquotes guard against them).

Exceptions are not referentially transparent which makes it harder to do stuff
like refactoring, move code around.  Tracking which statements are inside
try/catch blocks has a much higher cognitive burden than following type errors.

Exceptions make it hard/annoying to do error accumulation.  Both scalafix and
scalafmt work a lot with `Seq[Input].map(someScalametApp)` where error
accumulation is desired.

I don't think we can make the choice on behalf of the user whether an error
can be handled or not.  As @DavidDudson points out, library users of scalameta
range from cli, IDE integrations to macros. Each of these environments have
different ways to handle errors. Let the user decide.

Concrete places in the scalameta api where I'd like to get rid of exceptions in
favor of documenting errors in the type:

- Database.fromBytes. There's a whole swath of errors that can happen here in
  java.io or com.google.protobuf, I'd honestly go with `Try[Database]` since we
  don't want to loose the stack.
- Mirror.apply. Same as Database.fromBytes, Try. Users can do `Try[Mirror].get` if they don't care about error handling, but then it's their choice.
- AbsolutePath.apply. Instead of returning Option, we can do
```scala
object AbsolutePath {
  def userDir: AbsolutePath = ???
  def apply(path: String)(implicit userDir: AbsolutePath): AbsolutePath =
    if (isAbsolute(path)) new AbsolutePath(path) {}
    else userDir / path
}
...
AbsolutePath.userDir / "build.sbt"
// OR
AbsolutePath("build.sbt")(AbsolutePath.userDir)
// OR
implicit val userDir = AbsolutePath.userDir
AbsolutePath("build.sbt")
```

**Comment by olafurpg** [comment]
I'd like to add one example where exceptions make writing tools with meta extra difficult: `Symbol.apply`. Currently, `Symbol("blah")` throws an exception about an invalid symbol. It would be nicer IMO to get an `Either[String, Symbol]` or `Try[Symbol]`. I'm using `Symbol.apply` in scalafix to parse configuration into symbols and now I anticipate exceptions

```scala
  def parseSymbol(symbol: String): Configured[Symbol] =
    try Ok(Symbol(symbol))
    catch { case NonFatal(e) => ConfError(e) }
```
which not good IMO.

**Comment by olafurpg** [comment]
Contrib (and the syntactic API) has been stable for a while now and is working great. I don't imagine that we will be changing signatures of core methods in the near future. The repo currently uses a mix of exceptions and monads depending on the situation. We can leave the decision to code review during PRs when introducing new APIs.
