### ISSUE TITLE
Semantic information for Database.sugars

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#822]
#808 introduces a prototype implementation of infos and sugars that represents these introspection artifacts as strings. It turns out it's not that outrageous, because even strings can be extremely useful for code analysis tools.

However, we clearly need to provide more information to our users. Representing both infos and sugars as full-fledged trees sounds like a good idea.

**Comment by olafurpg** [comment]
I will take this on since I have an idea I'd like to try out.

I propose to

- Change `Sugar` message in schema
```proto
message Sugar {
  Range range = 1;
-  string syntax = 2;
+  Attributes attributes = 3;
}
``` 
- `Sugar.syntax` becomes `Sugar.attributes.contents`
- `m.Database.sugar(pos)` returns `Stat` instead of `String`.
  - sugars at the same position are concatenated, example `[1..1) [T]` and `[1..1) (blah)` becomes `[1..1) [T](blah)`. The ordering used for concatenation is 1) .apply 2) type params 3) implicit args.
  - Database.names includes names from nested sugars, this makes it possible to do `name.symbol` on names inside the returned Stat using the root Database.
  - If `Sugar.attributes.contents` does not parse as a Stat, then we prefix it with `*`. Example, `.apply => *.apply`/ `[T] => *[T]`/`implicitConf(*)(args)` is unchanged. The `*` identifier resolves to the symbol `_root_.scala.meta.sugar`.
  - other magic terms like `*` in `conversion(*)(arg)` also resolve to the symbol `_root_.scala.meta.sugar`.

**Comment by olafurpg** [comment]
#1000 took the first steps towards fixing this problem. The PR added two data structures `Input.Sugar` and `semantic.Sugar`, which can be used to attribute "invisible code". Now that this model is merged, I propose we 
- close this issue
- delegate Database.denotations to #1015
- open separate issues for bugs/rfe on the new model to attribute sugar
