### ISSUE TITLE
Semanticdb bytes are not concatenable

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#867]
Semanticdb [Attributes have no `path` field](https://github.com/scalameta/scalameta/blob/16fda03f70671db1c822b329beef2ac0dbb0dbdb/scalameta/semantic/shared/src/main/protobuf/semanticdb.proto#L7). The path name to the original source is inferred from the path to the `.semanticdb` file. This makes it problematic to combine multiple `.semanticdb` files into a single fat `.semanticdb` file.

I propose that we add a `path` field to Attributes and stop giving meaning to the filename of the `.semanticdb` files.

**Comment by xeno-by** [comment]
I don't think we can stop giving meaning to relative paths of `.semanticdb` files, because of how incremental compilation works. 

However, I agree with adding `s.Attributes.name` in order to better support fat dbs. Then, I guess, we should also change `s.Database` to say `entries: Seq[Attributes]` instead of `entries: Seq[(RelativePath, Attributes)]`.

**Comment by olafurpg** [comment]
> then, I guess, we should also change s.Database to say entries: Seq[Attributes] instead of entries: Seq[(RelativePath, Attributes)].

Correct. Does this merit postponing v1.8 a wee bit longer? I can fix this tomorrow morning.

**Comment by xeno-by** [comment]
I think we can postpone, yeah
