### ISSUE TITLE
Rethink Mirror

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#880]
This idea is prompted by the fact that we forgot to add the `Mirror.apply(Classpath)` overload in consistency with the recently introduced `Database.load(Classpath)`.

Back then, when `Mirror` was unrelated to `Database`, it seemed reasonable to have two different APIs to create these entities. But now that we have `Database <: Mirror`, maybe we should just retire `Mirror.apply`?

**Comment by olafurpg** [comment]
Do we have plans to add database-unrelated fields to Mirror? I personally would find Mirror.classapath/sourcepath/compilerOptions useful (see https://github.com/scalameta/scalameta/issues/944). I don't know how that would work for combined mirrors from different contexts.

**Comment by xeno-by** [comment]
See https://github.com/scalameta/scalameta/issues/964

**Comment by xeno-by** [comment]
See https://github.com/scalameta/scalameta/issues/944

**Comment by olafurpg** [comment]
What is the actionable item in this ticket? I'm OK with removing Mirror.apply and keeping things otherwise unchanged. I'd like to note however that the `Mirror` interface does not serve a real purpose since all it does it provide `Mirror.database: Database`.

**Comment by xeno-by** [comment]
The actionable item is to figure out the desired API for `Mirror`. I hope to get to this on Sunday.

**Comment by olafurpg** [comment]
scala.meta.Mirror disappeared in #1055. In scalafix, I have introduced a new class called `scalafix.SemanticCtx` which replaces my previous usage of Mirror. I am personally very happy with `SemanticCtx` since it allows me to add custom stuff that might otherwise not make it into `scala.meta.Mirror`. I propose we close this issue with "Mirror is gone, roll your own application-specific wrappers around scala.meta.Database".

**Comment by xeno-by** [comment]
The mirror is gone. The rethinking process is complete.
