### ISSUE TITLE
package object explore

### ISSUE THREAD

**Issue by paulp** [scalameta/scalameta#889]
allStatics seems to work most of the time, but see below. (Each package run twice to demonstrate non-determinism of error.) Why hard fail when you encounter a symbol you don't understand? It's not like a list obtained this way is reliably comprehensive anyway. It would be more useful if you issued a warning and returned all the symbols you could.

At a glance it looks like mostly it's java static members, but also there's the weird ant dependency. I guess scala-compiler.jar is still dragging around all that code compiled against ant, but it has no declared dependency on ant, so it will blow up if you inspect it too closely.

```scala
scala> org.scalameta.explore.allStatics("scala")
<console>:18: error: unsupported symbol value DEFAULT_MAX_SIZE: scala.tools.jline_embedded.console.history.MemoryHistory.DEFAULT_MAX_SIZE
       org.scalameta.explore.allStatics("scala")
                                       ^

scala> org.scalameta.explore.allStatics("scala")
<console>:18: error: Symbol 'term <none>.tools.ant' is missing from the classpath.
This symbol is required by 'class scala.tools.ant.sabbus.Make'.

Make sure that term ant is in your classpath and check for conflicting dependencies with -Ylog-classpath.
A full rebuild may help if Make.class was compiled against an incompatible version of <none>.tools.
       org.scalameta.explore.allStatics("scala")
                                        ^

scala> org.scalameta.explore.allStatics("scala.collection")
<console>:18: error: unsupported symbol value updater: scala.collection.concurrent.CNodeBase.updater
       org.scalameta.explore.allStatics("scala.collection")
                                       ^

scala> org.scalameta.explore.allStatics("scala.collection")
<console>:18: error: unsupported symbol value RESTART: scala.collection.concurrent.INodeBase.RESTART
       org.scalameta.explore.allStatics("scala.collection")
                                       ^
```

**Comment by xeno-by** [comment]
Hi @paulp! Glad you found these helpers useful. They are definitely helpful for us to keep our public API under control (I find mima to be to low-level for this purpose).

However, all code under org.scalameta is considered internal and is only maintained if it doesn't work for our particular use cases. These utilities is not our core competence, so dedicating significant chunks of time to them would deprive other more important parts of scalameta from our attention. We should've called that package `scala.meta.internal.helpers` or something.

If you'd be interested into extracting the metadata exploration functionality into a standalone library and maintaining it, we'd be happy to use your library instead of going with our own hacky solution.

**Comment by paulp** [comment]
Ok. Yes, it would be great if you could either make its status clear in the name of the package or add a comment to the file (this of course goes for whatever else is out there which is internal.) Otherwise each class involves a round of speculation about whether anyone is expected to be using it.

**Comment by xeno-by** [comment]
Thanks for the advice and the bug reports! I'll take care of internalization during the ongoing refactoring of scalameta.
