### ISSUE TITLE
Classify/label reported messages with unique ID

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#924]
We currently match against the "Unused import" string in several places

- https://github.com/scalacenter/scalafix/blob/8641796376b924d2d8719cfdc9c7c4975719569e/scalafix-core/src/main/scala/scalafix/rewrite/RemoveUnusedImports.scala#L11
- https://github.com/scalameta/scalameta/blob/a3b8b1f8c7fc7b75d6ea0663e5f3a39555fa574e/scalahost/nsc/src/main/scala/scala/meta/internal/semantic/AttributesOps.scala#L341

This approach has some problems
- not portable, what if the message is updated on the next Scala version? Is it "Unused import" in Dotty?
- it makes it hard to customize scalahost's behavior towards particular messages. For example, fatal warnings will all warnings into errors, even warnings that we can automatically with scalafix (like unused imports). It would be really nice if users could configure scalahost to collect unused import messages without emitting it to the console. Maybe https://github.com/scala/scala-dev/issues/333 can improve the situation.

Ideally, this should be baked into the Scala compiler. However, even if it does get into the compiler then we won't have it until 2.12.3 or 2.13 earliest and we are still not guaranteed that the IDs remain consistent across scalac/dotc.

I propose that we add a new `enum Id` field to `Message` in the semanticdb schema https://github.com/scalameta/scalameta/blob/master/scalameta/semantic/shared/src/main/protobuf/semanticdb.proto#L28 and then parse messages inside ScalahostReporter.

**Comment by xeno-by** [comment]
This makes sense.

I think I heard that the Dotty team already has error codes implemented. Is there an official documentation for that? /cc @felixmulder

**Comment by felixmulder** [comment]
There's not an official documentation on it, but yes - each error message does have a unique identifier.

It would be great to collaborate on this with the scalameta team and the scala2 team (ping @adriaanm) to have stable identifiers across both Dotty, Scalac and scalameta.

**Comment by felixmulder** [comment]
(note: our plan is to re-implement the error messages as enums when moving to only working on the bootstrapped compiler)

**Comment by xeno-by** [comment]
@felixmulder What kind of compatibility story can we expect from Dotty enums? Will we be able to link to that part of the Dotty compiler from Scala 2?

**Comment by felixmulder** [comment]
As you know, enum is a desugaring from:

```scala
enum Option[+T] {
  case Some[+T](t: T)
  case None
}
```

Into something like:

```scala
sealed abstract class Option[+T] extends scala.Enum
object Option {
  final case class Some[+T](t: T) extends Option[T] { val enumTag = 0 }
  final case object None extends Option[Nothing]    { val enumTag = 1 }
}
```

As such, for error messages you should be able to refer to the `enumTag` in the future.

Since we are currently writing the Dotty compiler in Scala 2 (might change to Dotty sometime in the not-too-distant future), we have opted for using a Java enum to get these unique identifiers ([ErrorMessageID.java](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/reporting/diagnostic/ErrorMessageID.java)). These enumeration values are used by the field `errorId`: [Message.scala#L36](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/reporting/diagnostic/Message.scala#L36)

So for compatibility there might be a point where the reference changes from `errorId` to `enumTag`. But we could just add a forwarder...

**Comment by xeno-by** [comment]
@olafurpg Is this ticket still relevant?

**Comment by olafurpg** [comment]
I still think this is an important use-case since we are currently matching against error messages by regexes. This feature is IMO a low-hanging fruit that plays nicely on the strengths of SemanticDB.

However, I don't have a concrete idea how to implement this feature on our side. I believe the best place to implement this is in the compiler using a similar solution as is done in Dotty.
